In [1]:
import os

DATA_FOLDER = '../00_data'
FIGURE_FOLDER = '../04_figures'

notebook_name = '005_filter_genes'

data_folder = os.path.join(DATA_FOLDER, notebook_name)
figure_folder = os.path.join(FIGURE_FOLDER, notebook_name)

print('Data folder for notebook:', data_folder)
print('Figure folder for notebook:', figure_folder)

! mkdir -p $figure_folder
! mkdir -p $data_folder

Data folder for notebook: ../00_data/005_filter_genes
Figure folder for notebook: ../04_figures/005_filter_genes


In [2]:
# Numerical python
import numpy as np

# Pandas for dataframes
import pandas as pd

# Labeled N-dimensional arrays
import xarray as xr

In [3]:
%matplotlib inline

In [4]:
input_folder = os.path.join(DATA_FOLDER, '003_make_combined_singlecell_fibroblast_datasets')
! ls -lh $input_folder

total 12234632
-rw-r--r--  1 olgabot  staff   5.8G Sep 29 17:17 cshl-fibroblast.netcdf


In [5]:
netcdf = os.path.join(input_folder, 'cshl-fibroblast.netcdf')
%time ds = xr.open_dataset(netcdf)

CPU times: user 68.5 ms, sys: 28.7 ms, total: 97.2 ms
Wall time: 163 ms


In [6]:
ds

<xarray.Dataset>
Dimensions:         (cell: 13300, gene: 58828)
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
  * gene            (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' ...
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...
Data variables:
    counts          (cell, gene) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

In [7]:
dir(ds)

['T',
 '_Dataset__default_attrs',
 '__abs__',
 '__abstractmethods__',
 '__add__',
 '__and__',
 '__array_priority__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__si

In [8]:
ds.var

<bound method ImplementsDatasetReduce._reduce_method.<locals>.wrapped_func of <xarray.Dataset>
Dimensions:         (cell: 13300, gene: 58828)
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
  * gene            (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' ...
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...
Data variables:
    counts          (cell, gene) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...>

In [9]:
ds.variablesables

Frozen(OrderedDict([('counts', <xarray.Variable (cell: 13300, gene: 58828)>
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])), ('group', <xarray.Variable (cell: 13300)>
array(['group1', 'group1', 'group1', ..., 'group8', 'group8', 'group8'], dtype=object)), ('cell_number', <xarray.Variable (cell: 13300)>
array(['c1', 'c2', 'c3', ..., 'c13298', 'c13299', 'c13300'], dtype=object)), ('group_permuted', <xarray.Variable (cell: 13300)>
array(['group3', 'group3', 'group2', ..., 'group4', 'group4', 'group3'], dtype=object)), ('gene', <xarray.IndexVariable 'gene' (gene: 58828)>
array(['5S_rRNA', '5_8S_rRNA', '7SK', ..., 'snosnR66', 'uc_338', 'yR211F11.2'], dtype=object)), ('cell', <xarray.IndexVariable 'cell' (cell: 13300)>
array(['group1_0000', 'group1_0001', 'group1_0002', ..., 'group8_0797',
       'group8_0798', 'group8_0799'], dtype=ob

In [31]:
counts0 = ds.counts == 0
counts0

<xarray.DataArray 'counts' (cell: 13300, gene: 58828)>
array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
  * gene            (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' ...
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...

In [32]:
~counts0.all(dim='cell')

<xarray.DataArray 'counts' (gene: 58828)>
array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)
Coordinates:
  * gene     (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' 'A1BG-AS1' ...

Remove genes that are 0 for all cells

In [33]:
ds_notall0 = ds.sel(gene=~counts0.all(dim='cell'))
ds_notall0

<xarray.Dataset>
Dimensions:         (cell: 13300, gene: 46243)
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
  * gene            (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' ...
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...
Data variables:
    counts          (cell, gene) int64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

In [34]:
netcdf = os.path.join(data_folder, 'cshl-fibroblast.netcdf')
ds_notall0.to_netcdf(netcdf)

In [35]:
ls -lh $data_folder

total 9618192
-rw-r--r--  1 olgabot  staff   4.6G Oct  5 13:44 cshl-fibroblast.netcdf


In [36]:
ds.counts.loc[:, '5_8S_rRNA',]

<xarray.DataArray 'counts' (cell: 13300)>
array([0, 0, 0, ..., 0, 0, 0])
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
    gene            <U9 '5_8S_rRNA'
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...

In [37]:
ds.counts.loc[:, ['5_8S_rRNA', 'RBFOX2']]

<xarray.DataArray 'counts' (cell: 13300, gene: 2)>
array([[0, 8],
       [0, 4],
       [0, 3],
       ..., 
       [0, 0],
       [0, 0],
       [0, 0]])
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
  * gene            (gene) object '5_8S_rRNA' 'RBFOX2'
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...

In [9]:
# ds['group'] = ('cell', ds.cell_metadata.sel(cell_feature='group'))
# ds['cell_number'] =   ('cell', ds.cell_metadata.sel(cell_feature='cell_number'))
# ds['group_permuted'] = ('cell', ds.cell_metadata.sel(cell_feature='group_permuted'))
# ds

In [10]:
len(ds.cell)

13300

In [30]:
# Set random seed for reproducibility
np.random.seed(0)

def select_random_cell_subset(x, threshold=0.1):
    """Get boolean numbers for each cell at particular frequencies
    
    Generate random numbers from 0-1 for each cell, and 
    take cells whose random numbers are below the threshold
    """
    random_bools = xr.DataArray(np.random.uniform(size=len(x.cell)) <= threshold,
                               coords=dict(cell=x.cell)) 
    return random_bools


subset_bools = ds.groupby('group').apply(select_random_cell_subset, 
                                                    threshold=0.1)
subset_bools

/Users/olgabot/anaconda3/envs/cshl-sca-2017/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: inferring DataArray dimensions from dictionary like ``coords`` has been deprecated. Use an explicit list of ``dims`` instead.
  


<xarray.DataArray (cell: 13300)>
array([False, False, False, ..., False, False, False], dtype=bool)
Coordinates:
  * cell            (cell) object 'group1_0000' 'group1_0001' 'group1_0002' ...
    cell_number     (cell) object 'c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8' ...
    group_permuted  (cell) object 'group3' 'group3' 'group2' 'group3' ...
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...

In [29]:
ds_subset = ds.sel(cell=subset_bools)
ds_subset

<xarray.Dataset>
Dimensions:         (cell: 1368, gene: 58828)
Coordinates:
    group           (cell) object 'group1' 'group1' 'group1' 'group1' ...
    cell_number     (cell) object 'c15' 'c16' 'c17' 'c35' 'c44' 'c68' 'c70' ...
    group_permuted  (cell) object 'group4' 'group4' 'group1' 'group5' ...
  * gene            (gene) object '5S_rRNA' '5_8S_rRNA' '7SK' 'A1BG' ...
  * cell            (cell) object 'group1_0014' 'group1_0015' 'group1_0016' ...
Data variables:
    counts          (cell, gene) int64 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ...

In [31]:
netcdf = os.path.join(data_folder, 'cshl-fibroblast-10percent.netcdf')
ds_subset.to_netcdf(netcdf)

## Write NetCDF

In [34]:
! ls -lh $data_folder

total 1263016
-rw-r--r--  1 olgabot  staff   617M Oct  5 13:33 cshl-fibroblast-10percent.netcdf


## Convert to pandas to write csvs

In [36]:
df = ds_subset.to_dataframe()
df.head()

counts   group cell_number group_permuted
cell        gene                                                
group1_0014 5S_rRNA         0  group1         c15         group4
            5_8S_rRNA       0  group1         c15         group4
            7SK             0  group1         c15         group4
            A1BG            0  group1         c15         group4
            A1BG-AS1        1  group1         c15         group4

### Reformat dataframes...

In [38]:
counts_tall = df['counts']
counts_2d = counts_tall.unstack()
counts_2d.head()

gene         5S_rRNA  5_8S_rRNA  7SK  A1BG  A1BG-AS1  A1CF  A2M  A2M-AS1  \
cell                                                                       
group1_0014        0          0    0     0         1     0    0        0   
group1_0015        0          0    0     0         0     0    0        0   
group1_0016        0          0    0     0         0     0    0        0   
group1_0034        0          0    0     0         0     0    0        0   
group1_0043        0          0    1     0         0     0    0        0   

gene         A2ML1  A2ML1-AS1     ...      snoU2-30  snoU2_19  snoU83B  \
cell                              ...                                    
group1_0014      0          0     ...             0         0        0   
group1_0015      0          0     ...             0         0        0   
group1_0016      0          0     ...             0         0        0   
group1_0034      0          0     ...             0         0        0   
group1_0043      0          0     ...             0         0        0   

gene         snoZ196  snoZ278  snoZ40  snoZ6  snosnR66  uc_338  yR211F11.2  
cell                                                                        
group1_0014        0        0       0      0         0       0           0  
group1_0015        0        0       0      0         0       0           0  
group1_0016        0        0       0      0         0       0           0  
group1_0034        0        0       0      0         0       0           0  
group1_0043        0        0       0      0         0       0           0  

[5 rows x 58828 columns]